#!/usr/bin/env node
import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

import { cleanMarkdown } from "./lib/clean.mjs";
import { fetchText, mapLimit } from "./lib/fetch.mjs";

const DEFAULT_BASE = "https://docs.typesafe.ai";
const INDEX_FILES = ["llms.txt", "llms-full.txt", "sitemap.xml"];
const FETCH_OPTIONS = { retries: 4, timeoutMs: 30_000 };

const USAGE = `Mirror ${DEFAULT_BASE} documentation into this repository.

Usage: node scripts/crawl.mjs [options]

Options:
  --check               Report drift without writing any file (exit 1 on drift)
  --prune               Delete mirrored files that are no longer in llms.txt
  --only=<page>         Process one page (repeatable), e.g. --only=concepts/state
  --concurrency=<n>     Parallel downloads, 1-32 (default 6)
  --out=<dir>           Repository root to write into (default ".")
  --base=<url>          Documentation origin (default ${DEFAULT_BASE})
  -h, --help            Show this help
`;

export function parseArgs(argv) {
  const options = {
    base: DEFAULT_BASE,
    out: ".",
    concurrency: 6,
    check: false,
    prune: false,
    only: [],
    help: false,
  };

  for (const arg of argv) {
    if (arg === "--check") options.check = true;
    else if (arg === "--prune") options.prune = true;
    else if (arg === "--help" || arg === "-h") options.help = true;
    else if (arg.startsWith("--concurrency=")) {
      options.concurrency = clampInteger(arg.slice("--concurrency=".length), 1, 32, "concurrency");
    } else if (arg.startsWith("--out=")) options.out = arg.slice("--out=".length);
    else if (arg.startsWith("--base=")) options.base = arg.slice("--base=".length).replace(/\/+$/, "");
    else if (arg.startsWith("--only=")) options.only.push(normalizePageKey(arg.slice("--only=".length)));
    else throw new Error(`unknown argument: ${arg}`);
  }

  return options;
}

export function parseIndex(markdown, base = DEFAULT_BASE) {
  const pages = [];
  const seen = new Set();

  for (const rawLine of markdown.split("\n")) {
    const match = /^-\s+\[([^\]]+)\]\(([^)\s]+)\)(?::\s*(.*))?\s*$/.exec(rawLine.trim());
    if (!match) continue;
    const [, title, url, description] = match;
    if (!url.startsWith(`${base}/`)) continue;
    const pagePath = url.slice(base.length + 1);
    if (!pagePath.endsWith(".md") || pagePath.includes("..") || seen.has(pagePath)) continue;
    seen.add(pagePath);
    pages.push({ title: title.trim(), url, description: (description ?? "").trim(), pagePath });
  }

  return pages;
}

export function extractSitemapPaths(xml, base = DEFAULT_BASE) {
  if (!xml) return [];
  const paths = [];
  for (const match of xml.matchAll(/<loc>\s*([^<\s]+)\s*<\/loc>/g)) {
    if (!match[1].startsWith(`${base}/`)) continue;
    const pagePath = match[1].slice(base.length + 1).replace(/\/+$/, "");
    if (pagePath === "" || pagePath.endsWith(".md")) continue;
    paths.push(pagePath);
  }
  return paths;
}

export function toPageKey(pagePath) {
  return pagePath.replace(/\.md$/, "").replace(/^\/+/, "");
}

export function renderToc(pages, { source = DEFAULT_BASE } = {}) {
  const lines = [
    "# TypeSafe documentation index",
    "",
    `Generated by \`scripts/crawl.mjs\` from <${source}/llms.txt>. Do not edit by hand.`,
    "",
    "| Page | Description |",
    "| --- | --- |",
  ];
  for (const page of pages) {
    lines.push(`| [${escapeCell(page.title)}](../docs/${page.pagePath}) | ${escapeCell(page.description)} |`);
  }
  lines.push("");
  return `${lines.join("\n")}\n`;
}

export function serializeManifest(base, entries) {
  const pages = {};
  for (const key of [...entries.keys()].sort()) pages[key] = entries.get(key);
  return `${JSON.stringify({ source: base, page_count: Object.keys(pages).length, pages }, null, 2)}\n`;
}

function clampInteger(value, min, max, label) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed < min || parsed > max) {
    throw new Error(`invalid --${label}: "${value}" (expected ${min}-${max})`);
  }
  return parsed;
}

function normalizePageKey(value) {
  return toPageKey(value.trim().replace(/^\.?\//, ""));
}

function escapeCell(value) {
  return String(value).replace(/\|/g, "\\|");
}

function sha256(text) {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

async function loadManifest(file) {
  try {
    const parsed = JSON.parse(await readFile(file, "utf8"));
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch (error) {
    if (error.code !== "ENOENT") console.warn(`warning: ignoring unreadable manifest: ${error.message}`);
    return {};
  }
}

async function readTextOrNull(file) {
  try {
    return await readFile(file, "utf8");
  } catch {
    return null;
  }
}

async function exists(file) {
  try {
    await stat(file);
    return true;
  } catch {
    return false;
  }
}

async function listFiles(dir) {
  try {
    const entries = await readdir(dir, { withFileTypes: true, recursive: true });
    return entries.filter((entry) => entry.isFile()).map((entry) => path.join(entry.parentPath, entry.name));
  } catch (error) {
    if (error.code === "ENOENT") return [];
    throw error;
  }
}

async function removeEmptyDirs(dir) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.isDirectory()) await removeEmptyDirs(path.join(dir, entry.name));
  }
  const remaining = await readdir(dir);
  if (remaining.length === 0) await rm(dir, { recursive: true, force: true });
}

async function writeText(file, content, check) {
  if (check) return;
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, content);
}

async function run() {
  const options = parseArgs(process.argv.slice(2));
  if (options.help) {
    process.stdout.write(USAGE);
    return 0;
  }

  const root = path.resolve(options.out);
  const manifestPath = path.join(root, "manifest.json");
  const previous = await loadManifest(manifestPath);
  const nextEntries = new Map(Object.entries(previous.pages ?? {}));

  console.log(`typesafe-docs: index <- ${options.base}/llms.txt`);
  const [llmsText, llmsFull, sitemapText] = await Promise.all([
    fetchText(`${options.base}/llms.txt`, FETCH_OPTIONS),
    fetchText(`${options.base}/llms-full.txt`, FETCH_OPTIONS).catch((error) => {
      console.warn(`warning: ${error.message}`);
      return null;
    }),
    fetchText(`${options.base}/sitemap.xml`, FETCH_OPTIONS).catch((error) => {
      console.warn(`warning: ${error.message}`);
      return null;
    }),
  ]);

  const pages = parseIndex(llmsText, options.base);
  if (pages.length === 0) throw new Error("llms.txt contained no document links");

  const pageSet = new Set(pages.map((page) => toPageKey(page.pagePath)));
  const warnings = [];
  const failures = [];
  const drift = [];

  const sitemapPaths = extractSitemapPaths(sitemapText, options.base);
  const sitemapKeys = new Set(sitemapPaths);
  for (const key of pageSet) {
    if (sitemapKeys.size > 0 && !sitemapKeys.has(key)) warnings.push(`in llms.txt but not in sitemap: ${key}`);
  }
  for (const key of sitemapKeys) {
    if (!pageSet.has(key)) warnings.push(`in sitemap but not in llms.txt: ${key}`);
  }

  const selected = options.only.length > 0
    ? pages.filter((page) => options.only.includes(toPageKey(page.pagePath)))
    : pages;
  if (selected.length === 0) throw new Error(`no pages matched --only=${options.only.join(",")}`);
  const coverage = options.only.length > 0 ? "partial" : "full";

  console.log(`typesafe-docs: ${selected.length}/${pages.length} pages, concurrency ${options.concurrency}${options.check ? ", check mode" : ""}`);
  const results = await mapLimit(selected, options.concurrency, async (page) => {
    try {
      return { page, raw: await fetchText(page.url, FETCH_OPTIONS) };
    } catch (error) {
      return { page, error };
    }
  });

  const stats = { added: 0, changed: 0, unchanged: 0, removed: 0, failed: 0 };
  let rawBytes = 0;
  let cleanBytes = 0;

  for (const result of results) {
    const { page } = result;
    if (result.error) {
      stats.failed += 1;
      failures.push(`${page.url} — ${result.error.message}`);
      continue;
    }

    const { text: cleanText, warnings: pageWarnings } = cleanMarkdown(result.raw, {
      pagePath: page.pagePath,
      pageSet,
      pageUrl: `${options.base}/${toPageKey(page.pagePath)}`,
      liveBase: options.base,
    });
    warnings.push(...pageWarnings);

    const rawFile = path.join(root, "raw", page.pagePath);
    const cleanFile = path.join(root, "docs", page.pagePath);
    const rawHash = sha256(result.raw);
    const cleanHash = sha256(cleanText);
    const prior = nextEntries.get(page.pagePath);
    const rawMissing = !(await exists(rawFile));
    const cleanMissing = !(await exists(cleanFile));
    const rawChanged = prior?.raw_sha256 !== rawHash;
    const cleanChanged = prior?.clean_sha256 !== cleanHash;

    rawBytes += Buffer.byteLength(result.raw);
    cleanBytes += Buffer.byteLength(cleanText);

    if (rawMissing || rawChanged || cleanMissing || cleanChanged) {
      if (options.check) {
        drift.push(`${page.pagePath}${prior ? "" : " (new)"}`);
      } else {
        if (rawChanged || rawMissing) await writeText(rawFile, result.raw, false);
        if (cleanChanged || cleanMissing) await writeText(cleanFile, cleanText, false);
      }
    }

    if (!prior) stats.added += 1;
    else if (rawChanged || cleanChanged) stats.changed += 1;
    else stats.unchanged += 1;

    nextEntries.set(page.pagePath, {
      url: page.url,
      title: page.title,
      description: page.description,
      raw_sha256: rawHash,
      clean_sha256: cleanHash,
      bytes: Buffer.byteLength(result.raw),
      changed_at: rawChanged ? new Date().toISOString() : (prior?.changed_at ?? new Date().toISOString()),
    });
  }

  if (coverage === "full") {
    const indexWrites = [
      [path.join(root, "index", "llms.txt"), llmsText],
      [path.join(root, "index", "sitemap.xml"), sitemapText],
      [path.join(root, "index", "llms-full.txt"), llmsFull],
      [path.join(root, "index", "README.md"), renderToc(pages, { source: options.base })],
    ];
    for (const [file, content] of indexWrites) {
      if (content === null) continue;
      const existing = await readTextOrNull(file);
      if (existing !== content) {
        if (options.check) drift.push(path.relative(root, file));
        else await writeText(file, content, false);
      }
    }

    if (options.prune && !options.check) {
      const indexPaths = new Set(pages.map((page) => page.pagePath));
      for (const dir of ["raw", "docs"]) {
        for (const file of await listFiles(path.join(root, dir))) {
          const relative = path.relative(path.join(root, dir), file);
          if (!indexPaths.has(relative)) {
            await rm(file, { force: true });
            stats.removed += 1;
          }
        }
        await removeEmptyDirs(path.join(root, dir));
      }
      for (const key of [...nextEntries.keys()]) {
        if (!indexPaths.has(key)) nextEntries.delete(key);
      }
    }

    const manifest = serializeManifest(options.base, nextEntries);
    if ((await readTextOrNull(manifestPath)) !== manifest) {
      if (options.check) drift.push("manifest.json");
      else await writeText(manifestPath, manifest, false);
    }
  }

  printSummary({ stats, rawBytes, cleanBytes, warnings, failures, drift, check: options.check });

  if (failures.length > 0) return 1;
  if (options.check && drift.length > 0) return 1;
  return 0;
}

function printSummary({ stats, rawBytes, cleanBytes, warnings, failures, drift, check }) {
  const format = (bytes) => `${(bytes / 1024 / 1024).toFixed(2)} MB`;
  console.log(
    `summary: added ${stats.added}, changed ${stats.changed}, unchanged ${stats.unchanged}, removed ${stats.removed}, failed ${stats.failed}`,
  );
  console.log(`size: raw ${format(rawBytes)}, clean ${format(cleanBytes)}`);
  for (const warning of [...new Set(warnings)]) console.log(`warning: ${warning}`);
  for (const failure of failures) console.log(`failure: ${failure}`);
  if (check) console.log(drift.length === 0 ? "check: up to date" : `check: drift detected in ${drift.length} file(s)`);
  for (const item of drift) console.log(`drift: ${item}`);
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  run()
    .then((code) => {
      process.exitCode = code;
    })
    .catch((error) => {
      console.error(`error: ${error.message}`);
      process.exitCode = 1;
    });
}
